branch-defaults:
  dev:
    application_name: heoweb
    default_platform: Node.js 18 running on 64bit Amazon Linux 2023
    default_region: us-west-1
    environment: heoweb-dev3
    group_suffix: null
  master:
    application_name: heo-web
    default_platform: Node.js 18 running on 64bit Amazon Linux 2023
    default_region: eu-west-2    
    environment: heo-apr21
  stage:
    application_name: heo-web
    default_platform: Node.js 18 running on 64bit Amazon Linux 2023
    default_region: eu-west-2
    environment: heo-june15
    group_suffix: null
environment-defaults:
  stage:
    branch: null
    repository: null
global:
  application_name: heo-web
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: heo
  repository: null
  sc: git
  workspace_type: Application
