const states = { 
  US : [
        {text:'Alabama',value:'AL'},
        {text:'Alaska',value:'AK'},
        {text:'Arizona',value:'AZ'},
        {text:'Arkansas',value:'AR'},
        {text:'California',value:'CA'},
        {text:'Colorado',value:'CO'},
        {text:'Connecticut',value:'CT'},
        {text:'Delaware',value:'DE'},
        {text:'District of Columbia',value:'DC'},
        {text:'Florida',value:'FL'},
        {text:'Georgia',value:'GA'},
        {text:'Hawaii',value:'HI'},
        {text:'Idaho',value:'ID'},
        {text:'Illinois',value:'IL'},
        {text:'Indiana',value:'IN'},
        {text:'Iowa',value:'IA'},
        {text:'Kansas',value:'KS'},
        {text:'Kentucky',value:'KY'},
        {text:'Louisiana',value:'LA'},
        {text:'Maine',value:'ME'},
        {text:'Maryland',value:'MD'},
        {text:'Massachusetts',value:'MA'},
        {text:'Michigan',value:'MI'},
        {text:'Minnesota',value:'MN'},
        {text:'Mississippi',value:'MS'},
        {text:'Missouri',value:'MO'},
        {text:'Montana',value:'MT'},
        {text:'Nebraska',value:'NE'},
        {text:'Nevada',value:'NV'},
        {text:'New Hampshire',value:'NH'},
        {text:'New Jersey',value:'NJ'},
        {text:'New Mexico',value:'NM'},
        {text:'New York',value:'NY'},
        {text:'North Carolina',value:'NC'},
        {text:'North Dakota',value:'ND'},
        {text:'Ohio',value:'OH'},
        {text:'Oklahoma',value:'OK'},
        {text:'Oregon',value:'OR'},
        {text:'Pennsylvania',value:'PA'},
        {text:'Rhode Island',value:'RI'},
        {text:'South Carolina',value:'SC'},
        {text:'South Dakota',value:'SD'},
        {text:'Tennessee',value:'TN'},
        {text:'Texas',value:'TX'},
        {text:'Utah',value:'UT'},
        {text:'Vermont',value:'VT'},
        {text:'Virginia',value:'VA'},
        {text:'Washington',value:'WA'},
        {text:'West Virginia',value:'WV'},
        {text:'Wisconsin',value:'WI'},
        {text:'Wyoming',value:'WY'}
      ],
      AU : [
        {text:'New South Wales',value:'NSW'},
        {text:'Victoria',value:'VIC'},
        {text:'Queensland', value:'QLD'},
        {text:'Tasmania',value:'TAS'},
        {text:'South Australia',value:'SA'},
        {text:'Western Australia',value:'WA'},
        {text:'Northern Territory',value:'NT'},
        {text:'Australian Capital Territory',value:'ACT'}
      ],
      CA : [
        {text: 'Alberta',value: 'AB'},
        {text: 'British Columbia',value: 'BC'},
        {text: 'Manitoba',value: 'MB'},
        {text: 'New Brunswick',value: 'NB'},
        {text: 'Newfoundland and Labrador',value: 'NL'},
        {text: 'Northwest Territories',value: 'NT'},
        {text: 'Nova Scotia',value: 'NS'},
        {text: 'Nunavut',value: 'NU'},
        {text: 'Ontario',value: 'ON'},
        {text: 'Prince Edward Island',value: 'PE'},
        {text: 'Quebec',value: 'QC'},
        {text: 'Saskatchewan',value: 'SK'},
        {text: 'Yukon Territory',value: 'YT'}
      ],
      MX : [
        {text: 'Distrito Federal', value: 'DIF'},
        {text: 'Aguascalientes', value: 'AGU'},
        {text: 'Baja California', value: 'BCN'},
        {text: 'Baja California Sur', value: 'BCS'},
        {text: 'Campeche', value: 'CAM'},
        {text: 'Chiapas', value: 'CHP'},
        {text: 'Chihuahua', value: 'CHH'},
        {text: 'Coahuila', value: 'COA'},
        {text: 'Colima', value: 'COL'},
        {text: 'Durango', value: 'DUR'},
        {text: 'Guanajuato', value: 'GUA'},
        {text: 'Guerrero', value: 'GRO'},
        {text: 'Hidalgo', value: 'HID'},
        {text: 'Jalisco', value: 'JAL'},
        {text: 'Michoacán', value: 'MIC'},
        {text: 'Morelos', value: 'MOR'},
        {text: 'México', value: 'MEX'},
        {text: 'Nayarit', value: 'NAY'},
        {text: 'Nuevo León', value: 'NLE'},
        {text: 'Oaxaca', value: 'OAX'},
        {text: 'Puebla', value: 'PUE'},
        {text: 'Querétaro', value: 'QUE'},
        {text: 'Quintana Roo', value: 'ROO'},
        {text: 'San Luis Potosí', value: 'SLP'},
        {text: 'Sinaloa', value: 'SIN'},
        {text: 'Sonora', value: 'SON'},
        {text: 'Tabasco', value: 'TAB'},
        {text: 'Tamaulipas', value: 'TAM'},
        {text: 'Tlaxcala', value: 'TLA'},
        {text: 'Veracruz', value: 'VER'},
        {text: 'Yucatán', value: 'YUC'},
        {text: 'Zacatecas', value: 'ZAC'}
      ]
};
  
  export default states;